### PR TITLE
Update explanation around the default.database

### PR DESCRIPTION
**Pull request by bradenkeith**

### CODE REVIEW

**Comment by luceos** [comment]
Dropping the reference to `database.default` makes its less easy to understand how the `.env` variable `DB_CONNECTION` binds into the Laravel ecosystem. I approve of the change, but not of dropping that configuration key.

As you must know, environment variables are no longer loaded when the config is cached with artisan config:cache.

**Comment by bradenkeith** [comment]
I see your point, but this is a non-standard way of talking about environmental variables within the Laravel ecosystem. The caching is typically something that happens without direct user interaction and is not referenced in their own code. They are best aware of utilizing ENV() to pull the correct variable and rely on Laravel to handle the magic behind the scenes.

Maybe I'm off track? I just don't see this type of verbiage in the Laravel documentation and think it would be wise to follow that vein of communication seeing as it covers the entire user base utilizing this documentation.

It may be a tenant package reference that I am just not aware of yet. I'm just getting started integrating this package with my application and have been trying to clean documentation that caused me to stumble as fresh eyes on the project.

How would you rewrite it to come to clarify the concept and keep the variables you wish to keep? I can provide feedback to if it makes sense to my fresh eyes, and you can decide what gets merged.

**Comment by luceos** [comment]
First off let me say thank you for your warm & friendly approach to these PRs. I'm very appreciative of you taking the effort to improve the parts of the documentation that are lacking. In fact most of the documentation can do with improvement, I promise to make the one for tenancy/tenancy the best ever and improve the one for Hyn as it get used. 

As to the question at hand:

> Most often it makes sense to use either `system` or `tenant` as your default database connection setting; this is `DB_CONNECTION` in your `.env` file.

I'd suggest something like:

> Most often it makes sense to use either `system` or `tenant` as your default database connection setting; this is `DB_CONNECTION` in your `.env` file. This environment variable is assigned to the `default` key in the `config/database.php` configuration file.

Thanks again for taking the time to get involved 🤗

**Comment by bradenkeith** [comment]
Happily. Always a pleasure to collaborate on open source projects we benefit from.

I think your final draft there is perfect. Very clear as to where the data originates and ends up.

**Comment by luceos** [comment]
Woop!

**Pull request merged**
