### PR TITLE
Added documentation for running migrations manually

### PR DESCRIPTION
**Pull request by Plytas**

### CODE REVIEW

**Comment by Plytas** [comment]
Don't merge yet. Gonna extract this bit to a separate tutorial page.

**Comment by Tofandel** [comment]
If you want it's possible to use the correct migration config when running the `migrate` command without having to specify path or database

This is how I do it
```php
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Symfony\Component\Console\Input\InputInterface;
use Tenancy\Facades\Tenancy;
use Tenancy\Hooks\Migration\Hooks\MigratesHook;
use Tenancy\Tenant\Events;

//Tenant model
public function tenantIdentificationByConsole( InputInterface $input )
    : ?Tenant {
        if ( $input->hasParameterOption( '--tenant' ) ) {
            $param = $input->getParameterOption( '--tenant' );
            $tenant = $this->query()
                ->where( 'name', $param )
                ->first();

            if ( ! $tenant ) {
                // It's important to stop the script if tenant is not found
                throw new ModelNotFoundException( 'Tenant "' . $param . '" was not found' );
            }
            // If command is namespaced with migrate
            if (strpos($input->getFirstArgument(), 'migrate') === 0) {
                // Resolve the config from our hooks
                app()->make(MigratesHook::class)->for(new Events\Created($tenant));
                app('migrator')->setConnection(Tenancy::getTenantConnectionName());
            }

            return $tenant;
        }
        return null;
    }
```

**Comment by ArlonAntonius** [comment]
Hi @Tofandel,

I really appreciate the feedback, but this will never be something that will be added by default to the `identification-driver-console`. All the packages are split and dependencies like this would not fit the ecosystem and our vision. We are working on a few things that will make this easier in the future, but we are not ready to release those yet.

I appreciate your somewhat hacky solutions, I hope it works well for you, I personally would really recommend you to move it out of the identification function though and simply create a new command for it.

If you have any questions, feel free to create a new issue regarding it :)

**Comment by Tofandel** [comment]
@ArlonAntonius I wasn't saying this terrible solution of a piece of code should be in the package ;) but having migration database and path automatically changed on the migrator when the tenant is identified using the `hooks-database` package. Which definitely fits the vision in my opinion and not having it seems actually more of a bug/missing feature

Eager to see those new tools though, this package is really great :+1:

**Comment by ArlonAntonius** [comment]
@Tofandel,

I'm not completely sure I get what you are saying. If you have time, would you be willing to explain your idea to me through [Our Discord Server](https://tenancy.dev/chat)? :)

**Comment by luceos** [comment]
Feel free to write the tutorial whenever and apply changes when needed.

**Pull request merged**
