### PR TITLE
Add providers list of tenancy for convenience

### PR DESCRIPTION
**Pull request by Tofandel**
Fixes https://github.com/tenancy/tenancy/issues/184

### CODE REVIEW

**Comment by ArlonAntonius** [comment]
I agree with you that we should probably provide this list somewhere. I was wondering, how would you feel about having every provider listed individually on the documentation page of the related packages under the installation section?

**Comment by sniper7kills** [comment]
This looks great!

**Comment by Tofandel** [comment]
@ArlonAntonius Yes adding also the name of the providers in the installation section of each module would be a great addition!

Like this I guess
### Providers
 - `Tenancy\Affects\Mails\Provider::class`

**Comment by Tofandel** [comment]
@ArlonAntonius Yes adding also the name of the providers in the installation section of each module would be a great addition!

Like this I guess

# Providers
- `Tenancy\Affects\Mails\Provider::class`

Edit: Guess it's already done, 2 fast 2 furious :dash:

**Comment by ArlonAntonius** [comment]
We tend to move fast when people have great suggestions 😉 Thanks for everything @Tofandel

**Pull request merged**
